name             'mariadb'
maintainer       'Karol Pasternak'
maintainer_email 'karol@pasternak.pro'
license          'All rights reserved'
description      'Installs/Configures mariadb'
long_description 'Installs/Configures mariadb'
version          '0.1.0'
depends          'yum'
