# Default version of MariaDB to install
# Can be overwritten in role/env/node
default[:mariadb][:server][:version] = "5.5"

# Secure install
default[:mariadb][:server][:remove][:test_db] = true

# Remove anonymous users
default[:mariadb][:server][:remove][:anon_users] = true
# Disallow root login remotely
default[:mariadb][:server][:remove][:remote_root] = true

# If nil it will be autogenerated
default[:mariadb][:server][:root_password] = nil
